included:
  - Sources
  - Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - fastlane
  - Build
  
disabled_rules:
  - no_space_in_method_call
  - todo
  - trailing_whitespace
  - unused_optional_binding
  - multiple_closures_with_trailing_closure
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment

opt_in_rules:
  - attributes 
  - closure_end_indentation
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  #- explicit_acl
  #- explicit_top_level_acl
  #- explicit_enum_raw_value
  - fatal_error_message
  - first_where
  - for_where
  #- implicitly_unwrapped_optional
  #- let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - trailing_newline
  - vertical_parameter_alignment_on_call
  - force_unwrapping
  - yoda_condition

function_parameter_count:
  - 6 # warning
  - 8 # error
type_name:
  min_length:
    error: 3
  max_length:
    warning: 60
    error: 60
identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 50
    error: 60
line_length:
  - 160 # warning
  - 180 # error
type_body_length:
  - 60 # warning
  - 80 # error
function_body_length:
  - 30 # warning
  - 40 # error
file_length:
  - 500 # warning
  - 600 # error
private_outlet:
  allow_private_set: true

force_cast: error

force_try: error

force_unwrapping: error
